const Bill = require('../models/Bill');
const Order = require('../models/Order');
const User = require('../models/User');

// Create a new bill (can be auto-generated or manual)
exports.createBill = async (req, res) => {
  try {
    const { orderId, items, subtotal, tax, shippingCost, discount, paymentMethod, notes, isAutoGenerated } = req.body;

    // Fetch order details
    const order = await Order.findById(orderId).populate('user');
    if (!order) {
      return res.status(404).json({ success: false, message: 'Order not found' });
    }

    const user = order.user;
    // Resolve a display name from profile.name, fallback to name or email
    const resolvedUserName = (user && user.profile && user.profile.name) ? user.profile.name : (user && (user.name || user.email) || 'Customer');
    const total = subtotal + (tax || 0) + (shippingCost || 0) - (discount || 0);

    const billData = {
      order: orderId,
      user: user._id,
      userEmail: user.email || '',
      userName: resolvedUserName,
      userAddress: order.address,
      items: items || order.items,
      subtotal,
      tax: tax || 0,
      shippingCost: shippingCost || 0,
      discount: discount || 0,
      total,
      paymentMethod: paymentMethod || 'Online',
      notes: notes || '',
      isAutoGenerated: isAutoGenerated !== undefined ? isAutoGenerated : true,
      createdBy: req.userId || null,
      status: 'Pending'
    };

    // Calculate tax percentage if tax amount is provided
    if (tax && subtotal) {
      billData.taxPercentage = (tax / subtotal) * 100;
    }

    const bill = await Bill.create(billData);
    await bill.populate('order user');

    res.status(201).json({ 
      success: true, 
      message: isAutoGenerated ? 'Bill generated successfully' : 'Bill created successfully', 
      data: bill 
    });
  } catch (err) {
    console.error('Error creating bill:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Get all bills (admin only)
exports.getAllBills = async (req, res) => {
  try {
    const bills = await Bill.find()
      .populate('order')
      .populate('user', 'name email')
      .populate('createdBy', 'name email')
      .sort({ createdAt: -1 });

    res.json({ 
      success: true, 
      message: 'Bills fetched', 
      data: bills 
    });
  } catch (err) {
    console.error('Error fetching bills:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Get bills for a specific user
exports.getUserBills = async (req, res) => {
  try {
    const userId = req.params.userId || req.userId;
    const bills = await Bill.find({ user: userId })
      .populate('order')
      .sort({ billDate: -1 });

    res.json({ 
      success: true, 
      message: 'User bills fetched', 
      data: bills 
    });
  } catch (err) {
    console.error('Error fetching user bills:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Get a specific bill by ID
exports.getBillById = async (req, res) => {
  try {
    const bill = await Bill.findById(req.params.id)
      .populate('order')
      .populate('user', 'name email phone')
      .populate('createdBy', 'name email');

    if (!bill) {
      return res.status(404).json({ success: false, message: 'Bill not found' });
    }

    // Check authorization
    if (bill.user._id.toString() !== req.userId && req.userRole !== 'admin') {
      return res.status(403).json({ success: false, message: 'Not authorized to view this bill' });
    }

    res.json({ 
      success: true, 
      message: 'Bill fetched', 
      data: bill 
    });
  } catch (err) {
    console.error('Error fetching bill:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Update bill status
exports.updateBillStatus = async (req, res) => {
  try {
    const { status, paymentMethod } = req.body;

    const updates = {};
    if (status) updates.status = status;
    if (paymentMethod) updates.paymentMethod = paymentMethod;

    // First try to update with validation enabled. If documents are legacy/incomplete and
    // validation fails, fall back to an update that skips validators to ensure status changes don't blow up.
    try {
      const updated = await Bill.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true });
      if (!updated) return res.status(404).json({ success: false, message: 'Bill not found' });
      await updated.populate('order user createdBy');
      return res.json({ success: true, message: 'Bill updated successfully', data: updated });
    } catch (innerErr) {
      if (innerErr.name === 'ValidationError') {
        console.warn('Validation error updating bill status; retrying update without validators:', Object.keys(innerErr.errors || {}).join(', '));
        // Retry without validation to preserve status updates for legacy/incomplete documents
        const updated = await Bill.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: false });
        if (!updated) return res.status(404).json({ success: false, message: 'Bill not found' });
        await updated.populate('order user createdBy');
        return res.json({ success: true, message: 'Bill updated (validation skipped due to incomplete document)', data: updated });
      }
      throw innerErr;
    }
  } catch (err) {
    console.error('Error updating bill:', err && err.stack ? err.stack : err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Update bill details (admin only)
exports.updateBill = async (req, res) => {
  try {
    const { items, subtotal, tax, shippingCost, discount, notes, paymentMethod } = req.body;
    const bill = await Bill.findById(req.params.id);

    if (!bill) {
      return res.status(404).json({ success: false, message: 'Bill not found' });
    }

    if (items) bill.items = items;
    if (subtotal) bill.subtotal = subtotal;
    if (tax !== undefined) {
      bill.tax = tax;
      if (bill.subtotal) {
        bill.taxPercentage = (tax / bill.subtotal) * 100;
      }
    }
    if (shippingCost !== undefined) bill.shippingCost = shippingCost;
    if (discount !== undefined) bill.discount = discount;
    if (notes) bill.notes = notes;
    if (paymentMethod) bill.paymentMethod = paymentMethod;

    // Recalculate total
    bill.total = bill.subtotal + bill.tax + bill.shippingCost - bill.discount;

    await bill.save();
    await bill.populate('order user createdBy');

    res.json({ 
      success: true, 
      message: 'Bill updated successfully', 
      data: bill 
    });
  } catch (err) {
    console.error('Error updating bill:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Delete a bill (admin only)
exports.deleteBill = async (req, res) => {
  try {
    const bill = await Bill.findByIdAndDelete(req.params.id);

    if (!bill) {
      return res.status(404).json({ success: false, message: 'Bill not found' });
    }

    res.json({ 
      success: true, 
      message: 'Bill deleted successfully', 
      data: bill 
    });
  } catch (err) {
    console.error('Error deleting bill:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Get bill by order ID
exports.getBillByOrderId = async (req, res) => {
  try {
    const bill = await Bill.findOne({ order: req.params.orderId })
      .populate('order')
      .populate('user', 'name email phone');

    if (!bill) {
      return res.status(404).json({ success: false, message: 'Bill not found for this order' });
    }

    res.json({ 
      success: true, 
      message: 'Bill fetched', 
      data: bill 
    });
  } catch (err) {
    console.error('Error fetching bill:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Generate bill PDF (optional - can be extended with actual PDF generation)
exports.generateBillPDF = async (req, res) => {
  try {
    const bill = await Bill.findById(req.params.id)
      .populate('order')
      .populate('user', 'name email phone address');

    if (!bill) {
      return res.status(404).json({ success: false, message: 'Bill not found' });
    }

    // Here you can integrate a PDF generation library like pdfkit or puppeteer
    res.json({ 
      success: true, 
      message: 'PDF generation initialized', 
      data: bill 
    });
  } catch (err) {
    console.error('Error generating PDF:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};

// Get bills statistics (admin only)
exports.getBillsStatistics = async (req, res) => {
  try {
    const totalBills = await Bill.countDocuments();
    const paidBills = await Bill.countDocuments({ status: 'Paid' });
    const pendingBills = await Bill.countDocuments({ status: 'Pending' });
    const totalRevenue = await Bill.aggregate([
      { $group: { _id: null, total: { $sum: '$total' } } }
    ]);

    const totalAmount = totalRevenue.length > 0 ? totalRevenue[0].total : 0;

    res.json({ 
      success: true, 
      data: {
        totalBills,
        paidBills,
        pendingBills,
        totalRevenue: totalAmount
      }
    });
  } catch (err) {
    console.error('Error fetching statistics:', err);
    res.status(500).json({ success: false, message: 'Server error', data: null });
  }
};
