require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const newProducts = [
  // Safety Equipment Category
  {
    name: 'Safety Harness Full Body',
    price: 4999,
    image: 'https://via.placeholder.com/300x300?text=Safety+Harness',
    category: 'Safety Equipment',
    brand: 'SafetyPro',
    color: 'Black',
    inStock: true,
    stock: 35,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 4299,
    discountPercent: 14,
    badge: 'Best Seller',
    description: 'Full-body safety harness with adjustable straps and D-rings.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'M-L'
  },
  {
    name: 'Safety Rope 50m',
    price: 3499,
    image: 'https://via.placeholder.com/300x300?text=Safety+Rope',
    category: 'Safety Equipment',
    brand: 'RopeGuard',
    color: 'White',
    inStock: true,
    stock: 25,
    isOffer: false,
    isBestSeller: false,
    badge: 'Strong',
    description: 'High-strength nylon safety rope rated for 1000kg load.',
    freeDelivery: false,
    deliveryPrice: 300,
    size: '50m'
  },
  {
    name: 'First Aid Kit Large',
    price: 2499,
    image: 'https://via.placeholder.com/300x300?text=First+Aid+Kit',
    category: 'First Aid',
    brand: 'MedCare',
    color: 'Red',
    inStock: true,
    stock: 60,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1999,
    discountPercent: 20,
    badge: 'Essential',
    description: 'Complete first aid kit with 150+ essential supplies.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Sign Board Set',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Safety+Signs',
    category: 'Signage',
    brand: 'SignMaster',
    color: 'Multi-color',
    inStock: true,
    stock: 45,
    isOffer: false,
    isBestSeller: false,
    badge: 'New',
    description: 'Set of 10 reflective safety warning signs.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Knee Pads Gel',
    price: 799,
    image: 'https://via.placeholder.com/300x300?text=Knee+Pads',
    category: 'Body Protection',
    brand: 'ComfortGuard',
    color: 'Black',
    inStock: true,
    stock: 90,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 599,
    discountPercent: 25,
    badge: 'Comfortable',
    description: 'Gel-padded knee pads for construction work.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'One Size'
  },
  {
    name: 'Face Shield Clear',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Face+Shield',
    category: 'Face Protection',
    brand: 'ShieldCare',
    color: 'Clear',
    inStock: true,
    stock: 150,
    isOffer: false,
    isBestSeller: true,
    badge: 'Popular',
    description: 'Transparent face shield for protection against splashes.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Work Light LED 100W',
    price: 2999,
    image: 'https://via.placeholder.com/300x300?text=LED+Work+Light',
    category: 'Lighting',
    brand: 'BrightWorks',
    color: 'Black',
    inStock: true,
    stock: 40,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 2499,
    discountPercent: 17,
    badge: 'Best Seller',
    description: '100W LED work light with stand and adjustable brightness.',
    freeDelivery: false,
    deliveryPrice: 200
  },
  {
    name: 'Safety Whistle',
    price: 149,
    image: 'https://via.placeholder.com/300x300?text=Safety+Whistle',
    category: 'Accessories',
    brand: 'AlertSound',
    color: 'Red',
    inStock: true,
    stock: 300,
    isOffer: false,
    isBestSeller: false,
    badge: 'Affordable',
    description: 'High-pitched safety whistle for emergency alerts.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Work Gloves Cotton',
    price: 349,
    image: 'https://via.placeholder.com/300x300?text=Cotton+Gloves',
    category: 'Gloves',
    brand: 'WorkComfort',
    color: 'White',
    inStock: true,
    stock: 200,
    isOffer: false,
    isBestSeller: false,
    badge: 'Lightweight',
    description: 'Breathable cotton work gloves with grip coating.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'L'
  },
  {
    name: 'Safety Cap',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Safety+Cap',
    category: 'Headwear',
    brand: 'HeadGuard',
    color: 'Yellow',
    inStock: true,
    stock: 85,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 449,
    discountPercent: 25,
    badge: 'Trending',
    description: 'Lightweight safety cap with reflective band.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'One Size'
  },

  // Additional Equipment
  {
    name: 'Tool Belt',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Tool+Belt',
    category: 'Storage',
    brand: 'ToolPro',
    color: 'Brown',
    inStock: true,
    stock: 55,
    isOffer: false,
    isBestSeller: true,
    badge: 'Best Seller',
    description: 'Heavy-duty leather tool belt with multiple pockets.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'L'
  },
  {
    name: 'Safety Glasses Anti-Scratch',
    price: 1199,
    image: 'https://via.placeholder.com/300x300?text=Safety+Glasses',
    category: 'Eye Protection',
    brand: 'ClearVision',
    color: 'Black',
    inStock: true,
    stock: 75,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 899,
    discountPercent: 25,
    badge: 'Top Rated',
    description: 'Anti-scratch and anti-fog safety glasses with UV protection.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Respirator Mask N95',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=N95+Mask',
    category: 'Respiratory Protection',
    brand: 'BreathEasy',
    color: 'White',
    inStock: true,
    stock: 500,
    isOffer: false,
    isBestSeller: true,
    badge: 'Popular',
    description: 'N95 certified respirator mask for dust and particle protection.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Work Shoes Steel Toe',
    price: 3299,
    image: 'https://via.placeholder.com/300x300?text=Work+Shoes',
    category: 'Footwear',
    brand: 'StrongFoot',
    color: 'Black',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 2799,
    discountPercent: 15,
    badge: 'Durable',
    description: 'Steel-toe work shoes with slip-resistant sole.',
    freeDelivery: false,
    deliveryPrice: 150,
    size: '10'
  },
  {
    name: 'Safety Lockout Hasp',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Lockout+Hasp',
    category: 'Safety Devices',
    brand: 'LockSafe',
    color: 'Red',
    inStock: true,
    stock: 120,
    isOffer: false,
    isBestSeller: false,
    badge: 'Industrial',
    description: 'Stainless steel lockout hasp for equipment safety.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Elbow Pads',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Elbow+Pads',
    category: 'Body Protection',
    brand: 'ProtectPlus',
    color: 'Black',
    inStock: true,
    stock: 70,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 549,
    discountPercent: 21,
    badge: 'Protective',
    description: 'Foam-padded elbow pads for construction work.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'M'
  },
  {
    name: 'Chemical Splash Apron',
    price: 1899,
    image: 'https://via.placeholder.com/300x300?text=Chemical+Apron',
    category: 'Protective Clothing',
    brand: 'ChemGuard',
    color: 'Yellow',
    inStock: true,
    stock: 35,
    isOffer: false,
    isBestSeller: false,
    badge: 'Specialized',
    description: 'Chemical-resistant apron for laboratory and industrial use.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Reflective Armband',
    price: 249,
    image: 'https://via.placeholder.com/300x300?text=Reflective+Armband',
    category: 'Visibility Gear',
    brand: 'VisibleNight',
    color: 'Orange',
    inStock: true,
    stock: 250,
    isOffer: false,
    isBestSeller: false,
    badge: 'Visibility',
    description: 'LED reflective armband for night visibility.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Pin Badge',
    price: 99,
    image: 'https://via.placeholder.com/300x300?text=Safety+Badge',
    category: 'Identification',
    brand: 'IDMark',
    color: 'Multi-color',
    inStock: true,
    stock: 500,
    isOffer: false,
    isBestSeller: false,
    badge: 'Affordable',
    description: 'Metal safety pin badge for identification and safety.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Emergency Eyewash Kit',
    price: 1599,
    image: 'https://via.placeholder.com/300x300?text=Eyewash+Kit',
    category: 'First Aid',
    brand: 'EmergencyFirst',
    color: 'Red',
    inStock: true,
    stock: 40,
    isOffer: false,
    isBestSeller: false,
    badge: 'Essential',
    description: 'Portable eyewash kit with sterile saline solution.',
    freeDelivery: true,
    deliveryPrice: 0
  },

  // More diverse products
  {
    name: 'Safety Ladder Stabilizer',
    price: 2199,
    image: 'https://via.placeholder.com/300x300?text=Ladder+Stabilizer',
    category: 'Access Equipment',
    brand: 'LadderPro',
    color: 'Yellow',
    inStock: true,
    stock: 30,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1799,
    discountPercent: 18,
    badge: 'Safety',
    description: 'Stabilizer bar for ladders to prevent slipping.',
    freeDelivery: false,
    deliveryPrice: 250
  },
  {
    name: 'Disposable Shoe Covers',
    price: 199,
    image: 'https://via.placeholder.com/300x300?text=Shoe+Covers',
    category: 'Protective Wear',
    brand: 'CleanStep',
    color: 'Blue',
    inStock: true,
    stock: 300,
    isOffer: false,
    isBestSeller: false,
    badge: 'Hygienic',
    description: 'Pack of 50 disposable non-slip shoe covers.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Carabiner Set',
    price: 899,
    image: 'https://via.placeholder.com/300x300?text=Carabiners',
    category: 'Climbing Gear',
    brand: 'GripSafe',
    color: 'Silver',
    inStock: true,
    stock: 65,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 699,
    discountPercent: 22,
    badge: 'Durable',
    description: 'Set of 5 aluminum safety carabiners with locking mechanism.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Anti-Static Wrist Strap',
    price: 349,
    image: 'https://via.placeholder.com/300x300?text=Wrist+Strap',
    category: 'Electronic Safety',
    brand: 'StaticFree',
    color: 'Black',
    inStock: true,
    stock: 180,
    isOffer: false,
    isBestSeller: false,
    badge: 'Electronic',
    description: 'Anti-static wrist strap for electronic component handling.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Hand Wash Station',
    price: 5999,
    image: 'https://via.placeholder.com/300x300?text=Wash+Station',
    category: 'Hygiene Equipment',
    brand: 'CleanHub',
    color: 'White',
    inStock: true,
    stock: 15,
    isOffer: false,
    isBestSeller: false,
    badge: 'Industrial',
    description: 'Portable hand wash station for outdoor work sites.',
    freeDelivery: false,
    deliveryPrice: 500
  },
  {
    name: 'Safety Mat Anti-Slip',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Safety+Mat',
    category: 'Floor Safety',
    brand: 'MatPro',
    color: 'Black',
    inStock: true,
    stock: 45,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 999,
    discountPercent: 23,
    badge: 'Best Seller',
    description: '3x2 meter anti-slip safety mat for wet areas.',
    freeDelivery: false,
    deliveryPrice: 300
  },
  {
    name: 'Tool Tether Set',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=Tool+Tether',
    category: 'Tool Safety',
    brand: 'SecureTools',
    color: 'Yellow',
    inStock: true,
    stock: 95,
    isOffer: false,
    isBestSeller: false,
    badge: 'Practical',
    description: 'Set of 10 tool tether straps to prevent tool drops.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Cones Reflective',
    price: 1599,
    image: 'https://via.placeholder.com/300x300?text=Safety+Cones',
    category: 'Site Safety',
    brand: 'ConeMaster',
    color: 'Orange',
    inStock: true,
    stock: 60,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1299,
    discountPercent: 19,
    badge: 'Reflective',
    description: 'Pack of 4 reflective traffic cones with reflective collars.',
    freeDelivery: false,
    deliveryPrice: 200
  },
  {
    name: 'Hearing Protection Earmuffs',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Earmuffs',
    category: 'Hearing Protection',
    brand: 'SoundShield',
    color: 'Black',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 999,
    discountPercent: 23,
    badge: 'Protective',
    description: 'Adjustable earmuffs with NRR 30 noise reduction rating.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Glasses Prescription Ready',
    price: 1699,
    image: 'https://via.placeholder.com/300x300?text=Prescription+Glasses',
    category: 'Eye Protection',
    brand: 'VisionPro',
    color: 'Black',
    inStock: true,
    stock: 35,
    isOffer: false,
    isBestSeller: false,
    badge: 'Premium',
    description: 'Prescription-ready safety glasses with anti-glare coating.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Traffic Control Paddle',
    price: 799,
    image: 'https://via.placeholder.com/300x300?text=Control+Paddle',
    category: 'Traffic Safety',
    brand: 'TrafficControl',
    color: 'Red',
    inStock: true,
    stock: 80,
    isOffer: false,
    isBestSeller: false,
    badge: 'Reflective',
    description: 'Stop/Slow traffic control paddle with reflective surface.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Line Rope Purple',
    price: 2299,
    image: 'https://via.placeholder.com/300x300?text=Purple+Rope',
    category: 'Access Equipment',
    brand: 'RopeLine',
    color: 'Purple',
    inStock: true,
    stock: 40,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1799,
    discountPercent: 22,
    badge: 'Durable',
    description: '30m high-strength safety rope with color marking.',
    freeDelivery: false,
    deliveryPrice: 200
  },
  {
    name: 'Overhead Fall Protection Kit',
    price: 7999,
    image: 'https://via.placeholder.com/300x300?text=Fall+Protection',
    category: 'Height Safety',
    brand: 'FallSafe',
    color: 'Black',
    inStock: true,
    stock: 10,
    isOffer: false,
    isBestSeller: false,
    badge: 'Professional',
    description: 'Complete overhead fall protection system with anchor point.',
    freeDelivery: false,
    deliveryPrice: 1000
  },
  {
    name: 'Work Gloves Leather',
    price: 799,
    image: 'https://via.placeholder.com/300x300?text=Leather+Gloves',
    category: 'Gloves',
    brand: 'LeatherGuard',
    color: 'Brown',
    inStock: true,
    stock: 75,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 599,
    discountPercent: 25,
    badge: 'Best Seller',
    description: 'Premium leather work gloves for heavy-duty tasks.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'L'
  },
  {
    name: 'Lens Cleaning Kit',
    price: 299,
    image: 'https://via.placeholder.com/300x300?text=Cleaning+Kit',
    category: 'Maintenance',
    brand: 'CleanLens',
    color: 'Multi-color',
    inStock: true,
    stock: 200,
    isOffer: false,
    isBestSeller: false,
    badge: 'Practical',
    description: 'Complete lens cleaning kit for safety glasses and goggles.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Work Overall Suit',
    price: 2499,
    image: 'https://via.placeholder.com/300x300?text=Overall+Suit',
    category: 'Protective Clothing',
    brand: 'DutyWear',
    color: 'Blue',
    inStock: true,
    stock: 45,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1999,
    discountPercent: 20,
    badge: 'Complete',
    description: 'Full-body work overall with multiple pockets and reflective strips.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'L'
  },
  {
    name: 'Safety Pin 2-pack',
    price: 199,
    image: 'https://via.placeholder.com/300x300?text=Safety+Pins',
    category: 'Fasteners',
    brand: 'SafePin',
    color: 'Silver',
    inStock: true,
    stock: 400,
    isOffer: false,
    isBestSeller: false,
    badge: 'Essential',
    description: 'Pack of 2 heavy-duty safety pins for equipment securing.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Glow Stick 12-pack',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Glow+Sticks',
    category: 'Visibility',
    brand: 'NightGlow',
    color: 'Multi-color',
    inStock: true,
    stock: 150,
    isOffer: false,
    isBestSeller: false,
    badge: 'Emergency',
    description: 'Pack of 12 glow sticks for emergency lighting.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Respirator Half Face',
    price: 1499,
    image: 'https://via.placeholder.com/300x300?text=Half+Respirator',
    category: 'Respiratory Protection',
    brand: 'BreathGuard',
    color: 'Black',
    inStock: true,
    stock: 55,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1199,
    discountPercent: 20,
    badge: 'Professional',
    description: 'Half-face respirator with replaceable filters.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Dust Mask Pack',
    price: 349,
    image: 'https://via.placeholder.com/300x300?text=Dust+Masks',
    category: 'Respiratory Protection',
    brand: 'DustFree',
    color: 'White',
    inStock: true,
    stock: 400,
    isOffer: false,
    isBestSeller: false,
    badge: 'Economy',
    description: 'Pack of 50 disposable dust masks with ear loops.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Scaffolding Tag Clip',
    price: 449,
    image: 'https://via.placeholder.com/300x300?text=Tag+Clip',
    category: 'Access Equipment',
    brand: 'ScaffoldPro',
    color: 'Yellow',
    inStock: true,
    stock: 110,
    isOffer: false,
    isBestSeller: false,
    badge: 'Industrial',
    description: 'Scaffolding tag clip for equipment identification.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Light Rechargeable',
    price: 1099,
    image: 'https://via.placeholder.com/300x300?text=LED+Light',
    category: 'Lighting',
    brand: 'ChargeLite',
    color: 'Black',
    inStock: true,
    stock: 70,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 799,
    discountPercent: 27,
    badge: 'Best Seller',
    description: 'Rechargeable LED safety light with adjustable brightness.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Inspection Mirror Long',
    price: 899,
    image: 'https://via.placeholder.com/300x300?text=Inspection+Mirror',
    category: 'Tools',
    brand: 'InspectPro',
    color: 'Black',
    inStock: true,
    stock: 60,
    isOffer: false,
    isBestSeller: false,
    badge: 'Useful',
    description: 'Long-reach inspection mirror with adjustable angle.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '1m'
  },
  {
    name: 'Protective Goggles Orange',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Orange+Goggles',
    category: 'Eye Protection',
    brand: 'OrangeGuard',
    color: 'Orange',
    inStock: true,
    stock: 85,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 549,
    discountPercent: 21,
    badge: 'Protective',
    description: 'Impact-resistant protective goggles with ventilation.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Safety Clips Metal',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=Safety+Clips',
    category: 'Fasteners',
    brand: 'MetalClip',
    color: 'Silver',
    inStock: true,
    stock: 150,
    isOffer: false,
    isBestSeller: false,
    badge: 'Strong',
    description: 'Pack of 10 metal safety clips for secure fastening.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Work Jacket High Visibility',
    price: 2199,
    image: 'https://via.placeholder.com/300x300?text=Work+Jacket',
    category: 'Protective Clothing',
    brand: 'VisibleWear',
    color: 'Orange',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 1799,
    discountPercent: 18,
    badge: 'Best Seller',
    description: 'High-visibility work jacket with reflective strips and pockets.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'L'
  },
  {
    name: 'Traction Cleats',
    price: 1599,
    image: 'https://via.placeholder.com/300x300?text=Traction+Cleats',
    category: 'Footwear Accessories',
    brand: 'GripStep',
    color: 'Black',
    inStock: true,
    stock: 40,
    isOffer: false,
    isBestSeller: false,
    badge: 'Winter',
    description: 'Universal traction cleats for icy and slippery surfaces.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Lubricant Spray Safety',
    price: 299,
    image: 'https://via.placeholder.com/300x300?text=Lubricant+Spray',
    category: 'Maintenance',
    brand: 'LubePro',
    color: 'Yellow',
    inStock: true,
    stock: 120,
    isOffer: false,
    isBestSeller: false,
    badge: 'Essential',
    description: 'Multi-purpose lubricant spray for equipment maintenance.',
    freeDelivery: true,
    deliveryPrice: 0
  }
];

mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    try {
      // Insert new products
      const products = await Product.insertMany(newProducts);
      console.log(`✅ Successfully added ${products.length} new products to the database!`);
      
      products.forEach((p, index) => {
        console.log(`${index + 1}. ${p.name} - $${p.price}`);
      });

      // Get total product count
      const totalProducts = await Product.countDocuments();
      console.log(`\n📊 Total products in database: ${totalProducts}`);

      process.exit(0);
    } catch (err) {
      console.error('Error:', err.message);
      process.exit(1);
    }
  })
  .catch(err => {
    console.error('MongoDB connection error:', err.message);
    process.exit(1);
  });
