require('dotenv').config();
const mongoose = require('mongoose');
const Accessory = require('../models/Accessory');

// Connection string - update if needed
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/project-grp';

const accessoriesData = [
  {
    name: "Premium Phone Case",
    price: 599,
    image: "https://via.placeholder.com/300?text=Phone+Case",
    category: "Phone Accessories",
    brand: "TechShield",
    color: "Black",
    inStock: true,
    stock: 50,
    isBestSeller: true,
    badge: "Popular",
    description: "Durable and stylish phone case with shock protection",
    discountPercent: 10,
    freeDelivery: true,
    size: "One Size",
    tags: "phone,case,protection"
  },
  {
    name: "USB-C Charging Cable",
    price: 349,
    image: "https://via.placeholder.com/300?text=USB+Cable",
    category: "Cables & Chargers",
    brand: "PowerTech",
    color: "White",
    inStock: true,
    stock: 100,
    isBestSeller: true,
    badge: "Fast Charging",
    description: "5A fast charging USB-C cable, 2 meters long",
    discountPercent: 15,
    freeDelivery: true,
    size: "2M",
    tags: "charging,cable,usb-c"
  },
  {
    name: "Screen Protector Tempered Glass",
    price: 199,
    image: "https://via.placeholder.com/300?text=Screen+Protector",
    category: "Screen Protection",
    brand: "CrystalGuard",
    color: "Clear",
    inStock: true,
    stock: 75,
    badge: "Best Protection",
    description: "Tempered glass screen protector with anti-fingerprint coating",
    discountPercent: 5,
    freeDelivery: true,
    size: "Universal",
    tags: "screen,protection,glass"
  },
  {
    name: "Wireless Earbuds",
    price: 2499,
    image: "https://via.placeholder.com/300?text=Earbuds",
    category: "Audio",
    brand: "SoundMax",
    color: "Black",
    inStock: true,
    stock: 30,
    isBestSeller: true,
    badge: "Premium",
    description: "True wireless earbuds with noise cancellation and 30hr battery",
    discountPercent: 20,
    freeDelivery: true,
    offerPrice: 1999,
    size: "One Size",
    tags: "earbuds,wireless,audio"
  },
  {
    name: "Phone Stand Desktop",
    price: 449,
    image: "https://via.placeholder.com/300?text=Phone+Stand",
    category: "Phone Accessories",
    brand: "DeskPro",
    color: "Silver",
    inStock: true,
    stock: 40,
    description: "Adjustable aluminum phone stand for desk",
    discountPercent: 8,
    freeDelivery: true,
    size: "Universal",
    tags: "stand,desktop,holder"
  },
  {
    name: "Portable Power Bank 20000mAh",
    price: 1299,
    image: "https://via.placeholder.com/300?text=Power+Bank",
    category: "Power Solutions",
    brand: "ChargeMax",
    color: "Black",
    inStock: true,
    stock: 45,
    isBestSeller: true,
    badge: "High Capacity",
    description: "20000mAh power bank with dual USB ports and LED display",
    discountPercent: 12,
    freeDelivery: true,
    offerPrice: 1139,
    size: "Compact",
    tags: "powerbank,charging,portable"
  },
  {
    name: "HDMI Cable 2.0",
    price: 299,
    image: "https://via.placeholder.com/300?text=HDMI+Cable",
    category: "Cables & Chargers",
    brand: "ConnectPro",
    color: "Black",
    inStock: true,
    stock: 60,
    description: "4K HDMI 2.0 cable 3 meters compatible with all devices",
    discountPercent: 10,
    freeDelivery: true,
    size: "3M",
    tags: "hdmi,cable,video"
  },
  {
    name: "Laptop Cooling Pad",
    price: 1899,
    image: "https://via.placeholder.com/300?text=Cooling+Pad",
    category: "Laptop Accessories",
    brand: "CoolTech",
    color: "Black",
    inStock: true,
    stock: 25,
    badge: "Efficient",
    description: "RGB laptop cooling pad with 5 fans and USB-A connector",
    discountPercent: 15,
    freeDelivery: true,
    size: "Universal",
    tags: "cooling,laptop,pad"
  },
  {
    name: "Keyboard Mouse Combo Wireless",
    price: 1499,
    image: "https://via.placeholder.com/300?text=Keyboard+Mouse",
    category: "Computer Accessories",
    brand: "TechGear",
    color: "Black",
    inStock: true,
    stock: 35,
    isBestSeller: true,
    description: "Wireless keyboard and mouse combo with 2.4GHz connection",
    discountPercent: 18,
    freeDelivery: true,
    size: "Standard",
    tags: "keyboard,mouse,wireless"
  },
  {
    name: "USB Hub 4-Port",
    price: 699,
    image: "https://via.placeholder.com/300?text=USB+Hub",
    category: "Computer Accessories",
    brand: "PortConnect",
    color: "Silver",
    inStock: true,
    stock: 50,
    description: "4-port USB 3.0 hub with independent switches",
    discountPercent: 8,
    freeDelivery: true,
    size: "One Size",
    tags: "hub,usb,ports"
  },
  {
    name: "Webcam 1080p HD",
    price: 2299,
    image: "https://via.placeholder.com/300?text=Webcam",
    category: "Computer Accessories",
    brand: "VisionTech",
    color: "Black",
    inStock: true,
    stock: 20,
    isBestSeller: true,
    badge: "Full HD",
    description: "1080p HD webcam with auto-focus and built-in microphone",
    discountPercent: 12,
    freeDelivery: true,
    size: "One Size",
    tags: "webcam,video,camera"
  },
  {
    name: "Microphone USB Condenser",
    price: 3499,
    image: "https://via.placeholder.com/300?text=Microphone",
    category: "Audio",
    brand: "AudioPro",
    color: "Black",
    inStock: true,
    stock: 15,
    badge: "Professional",
    description: "Professional USB condenser microphone with tripod stand",
    discountPercent: 20,
    freeDelivery: true,
    size: "Standard",
    tags: "microphone,audio,professional"
  },
  {
    name: "Headphone Stand",
    price: 299,
    image: "https://via.placeholder.com/300?text=Headphone+Stand",
    category: "Audio",
    brand: "DeskOrganizer",
    color: "Black",
    inStock: true,
    stock: 55,
    description: "Sturdy headphone stand with non-slip base",
    discountPercent: 5,
    freeDelivery: true,
    size: "Universal",
    tags: "stand,headphone,holder"
  },
  {
    name: "Lightning Cable 2M",
    price: 399,
    image: "https://via.placeholder.com/300?text=Lightning+Cable",
    category: "Cables & Chargers",
    brand: "AppleGear",
    color: "White",
    inStock: true,
    stock: 70,
    isBestSeller: true,
    description: "Apple MFi certified Lightning cable 2 meters",
    discountPercent: 10,
    freeDelivery: true,
    size: "2M",
    tags: "lightning,cable,apple"
  },
  {
    name: "Tablet Stand Adjustable",
    price: 549,
    image: "https://via.placeholder.com/300?text=Tablet+Stand",
    category: "Tablet Accessories",
    brand: "FlexiStand",
    color: "Silver",
    inStock: true,
    stock: 45,
    description: "Adjustable tablet stand for all sizes 4-10 inches",
    discountPercent: 12,
    freeDelivery: true,
    size: "Universal",
    tags: "tablet,stand,holder"
  },
  {
    name: "Stylus Pen Digital",
    price: 1899,
    image: "https://via.placeholder.com/300?text=Stylus+Pen",
    category: "Tablet Accessories",
    brand: "DigitalPen",
    color: "Black",
    inStock: true,
    stock: 30,
    badge: "Precision",
    description: "Digital stylus pen with pressure sensitivity for drawing",
    discountPercent: 15,
    freeDelivery: true,
    size: "One Size",
    tags: "stylus,pen,digital"
  },
  {
    name: "Phone Ring Holder",
    price: 149,
    image: "https://via.placeholder.com/300?text=Ring+Holder",
    category: "Phone Accessories",
    brand: "MobileGrip",
    color: "Gold",
    inStock: true,
    stock: 100,
    description: "360 degree rotating phone ring holder",
    discountPercent: 5,
    freeDelivery: true,
    size: "Universal",
    tags: "ring,holder,phone"
  },
  {
    name: "Car Phone Mount Dashboard",
    price: 399,
    image: "https://via.placeholder.com/300?text=Car+Mount",
    category: "Phone Accessories",
    brand: "DriveSafe",
    color: "Black",
    inStock: true,
    stock: 50,
    description: "Suction cup car phone mount with 360 rotation",
    discountPercent: 8,
    freeDelivery: true,
    size: "Universal",
    tags: "mount,car,phone"
  },
  {
    name: "Screen Cleaning Kit",
    price: 199,
    image: "https://via.placeholder.com/300?text=Cleaning+Kit",
    category: "Cleaning & Care",
    brand: "CleenTech",
    color: "Blue",
    inStock: true,
    stock: 80,
    description: "Complete screen cleaning kit with microfiber cloth and solution",
    discountPercent: 5,
    freeDelivery: true,
    size: "One Size",
    tags: "cleaning,screen,care"
  },
  {
    name: "Air Duster Compressed Electric",
    price: 799,
    image: "https://via.placeholder.com/300?text=Air+Duster",
    category: "Cleaning & Care",
    brand: "TechClean",
    color: "Black",
    inStock: true,
    stock: 35,
    badge: "Portable",
    description: "Electric air duster for cleaning keyboards and devices",
    discountPercent: 10,
    freeDelivery: true,
    size: "Compact",
    tags: "duster,cleaning,portable"
  },
  {
    name: "Laptop Bag 17 Inch",
    price: 1299,
    image: "https://via.placeholder.com/300?text=Laptop+Bag",
    category: "Laptop Accessories",
    brand: "CarryPro",
    color: "Black",
    inStock: true,
    stock: 40,
    isBestSeller: true,
    description: "Water-resistant laptop backpack for 17 inch laptops",
    discountPercent: 12,
    freeDelivery: true,
    size: "17 Inch",
    tags: "bag,laptop,backpack"
  },
  {
    name: "Laptop Skin Protector",
    price: 349,
    image: "https://via.placeholder.com/300?text=Laptop+Skin",
    category: "Laptop Accessories",
    brand: "StyleTech",
    color: "Silver",
    inStock: true,
    stock: 60,
    description: "Premium laptop skin with easy application and removal",
    discountPercent: 8,
    freeDelivery: true,
    size: "13-17 Inch",
    tags: "skin,protection,laptop"
  },
  {
    name: "Monitor Stand Riser",
    price: 1199,
    image: "https://via.placeholder.com/300?text=Monitor+Stand",
    category: "Computer Accessories",
    brand: "DeskErgonomic",
    color: "Black",
    inStock: true,
    stock: 30,
    description: "Adjustable monitor stand with storage compartment",
    discountPercent: 10,
    freeDelivery: true,
    size: "Universal",
    tags: "stand,monitor,riser"
  },
  {
    name: "Desk Lamp LED Adjustable",
    price: 899,
    image: "https://via.placeholder.com/300?text=Desk+Lamp",
    category: "Lighting",
    brand: "BrightLight",
    color: "White",
    inStock: true,
    stock: 45,
    badge: "Energy Efficient",
    description: "LED desk lamp with 5 brightness levels and USB charging",
    discountPercent: 15,
    freeDelivery: true,
    size: "Standard",
    tags: "lamp,led,lighting"
  },
  {
    name: "Cable Organizer Set",
    price: 299,
    image: "https://via.placeholder.com/300?text=Cable+Organizer",
    category: "Organization",
    brand: "NeatTech",
    color: "Black",
    inStock: true,
    stock: 70,
    description: "5-piece cable organizer set for desk and home",
    discountPercent: 5,
    freeDelivery: true,
    size: "One Size",
    tags: "organizer,cable,desk"
  },
  {
    name: "Mouse Pad Large Gaming",
    price: 599,
    image: "https://via.placeholder.com/300?text=Mouse+Pad",
    category: "Computer Accessories",
    brand: "GamerGear",
    color: "Black",
    inStock: true,
    stock: 55,
    isBestSeller: true,
    description: "Large gaming mouse pad with non-slip rubber base",
    discountPercent: 12,
    freeDelivery: true,
    size: "80x40cm",
    tags: "mousepad,gaming,desk"
  },
  {
    name: "Gaming Headset 7.1 Surround",
    price: 3299,
    image: "https://via.placeholder.com/300?text=Gaming+Headset",
    category: "Audio",
    brand: "GamerMax",
    color: "Black",
    inStock: true,
    stock: 25,
    isBestSeller: true,
    badge: "Pro Gaming",
    description: "7.1 surround sound gaming headset with RGB lighting",
    discountPercent: 18,
    freeDelivery: true,
    offerPrice: 2699,
    size: "One Size",
    tags: "headset,gaming,audio"
  },
  {
    name: "Controller Gamepad Wireless",
    price: 2499,
    image: "https://via.placeholder.com/300?text=Gamepad",
    category: "Gaming",
    brand: "GameTech",
    color: "Black",
    inStock: true,
    stock: 40,
    description: "Wireless gaming controller compatible with PC and consoles",
    discountPercent: 15,
    freeDelivery: true,
    size: "Standard",
    tags: "gamepad,controller,wireless"
  },
  {
    name: "Memory Card 128GB MicroSD",
    price: 799,
    image: "https://via.placeholder.com/300?text=Memory+Card",
    category: "Storage",
    brand: "StoragePro",
    color: "Blue",
    inStock: true,
    stock: 50,
    isBestSeller: true,
    badge: "Fast Speed",
    description: "128GB Class 10 MicroSD card with high speed transfer",
    discountPercent: 10,
    freeDelivery: true,
    size: "128GB",
    tags: "memory,card,storage"
  },
  {
    name: "USB Flash Drive 64GB",
    price: 599,
    image: "https://via.placeholder.com/300?text=USB+Flash",
    category: "Storage",
    brand: "DataKeep",
    color: "Black",
    inStock: true,
    stock: 60,
    description: "64GB USB 3.0 flash drive with fast data transfer",
    discountPercent: 8,
    freeDelivery: true,
    size: "64GB",
    tags: "usb,flash,storage"
  },
  {
    name: "Portable SSD 512GB",
    price: 4999,
    image: "https://via.placeholder.com/300?text=Portable+SSD",
    category: "Storage",
    brand: "QuickStorage",
    color: "Silver",
    inStock: true,
    stock: 20,
    isBestSeller: true,
    badge: "Ultra Fast",
    description: "512GB portable SSD with USB-C connection and 1000MB/s speed",
    discountPercent: 12,
    freeDelivery: true,
    offerPrice: 4399,
    size: "512GB",
    tags: "ssd,storage,portable"
  },
  {
    name: "Router WiFi 6 Mesh",
    price: 5999,
    image: "https://via.placeholder.com/300?text=WiFi+Router",
    category: "Networking",
    brand: "NetMax",
    color: "White",
    inStock: true,
    stock: 15,
    isBestSeller: true,
    badge: "WiFi 6",
    description: "Mesh WiFi 6 router system with 3000Mbps speed",
    discountPercent: 15,
    freeDelivery: true,
    offerPrice: 5099,
    size: "One Size",
    tags: "router,wifi,networking"
  },
  {
    name: "Ethernet Cable Cat6 5M",
    price: 399,
    image: "https://via.placeholder.com/300?text=Ethernet+Cable",
    category: "Cables & Chargers",
    brand: "NetConnect",
    color: "Blue",
    inStock: true,
    stock: 80,
    description: "Cat6 ethernet cable 5 meters with gold plated connectors",
    discountPercent: 5,
    freeDelivery: true,
    size: "5M",
    tags: "ethernet,cable,networking"
  },
  {
    name: "VGA Cable Adapter",
    price: 299,
    image: "https://via.placeholder.com/300?text=VGA+Cable",
    category: "Cables & Chargers",
    brand: "AdapterPro",
    color: "Black",
    inStock: true,
    stock: 70,
    description: "VGA to VGA cable 3 meters for monitors and projectors",
    discountPercent: 5,
    freeDelivery: true,
    size: "3M",
    tags: "vga,cable,adapter"
  },
  {
    name: "Audio Jack 3.5mm Splitter",
    price: 149,
    image: "https://via.placeholder.com/300?text=Audio+Splitter",
    category: "Audio",
    brand: "SoundConnect",
    color: "Black",
    inStock: true,
    stock: 90,
    description: "3.5mm audio jack splitter for dual headphones",
    discountPercent: 5,
    freeDelivery: true,
    size: "One Size",
    tags: "audio,splitter,jack"
  },
  {
    name: "Bluetooth Speaker Portable",
    price: 2199,
    image: "https://via.placeholder.com/300?text=BT+Speaker",
    category: "Audio",
    brand: "SoundWave",
    color: "Blue",
    inStock: true,
    stock: 35,
    isBestSeller: true,
    badge: "Waterproof",
    description: "Waterproof Bluetooth speaker with 20W output and 12hr battery",
    discountPercent: 12,
    freeDelivery: true,
    offerPrice: 1935,
    size: "Compact",
    tags: "speaker,bluetooth,portable"
  },
  {
    name: "Phone Camera Lens Protector",
    price: 249,
    image: "https://via.placeholder.com/300?text=Lens+Protector",
    category: "Phone Accessories",
    brand: "CameraGuard",
    color: "Clear",
    inStock: true,
    stock: 75,
    description: "Tempered glass camera lens protector with anti-scratch coating",
    discountPercent: 8,
    freeDelivery: true,
    size: "Universal",
    tags: "lens,camera,protector"
  },
  {
    name: "Battery Charger Intelligent",
    price: 799,
    image: "https://via.placeholder.com/300?text=Battery+Charger",
    category: "Power Solutions",
    brand: "PowerCharge",
    color: "Black",
    inStock: true,
    stock: 50,
    description: "Intelligent battery charger for AA/AAA with LED display",
    discountPercent: 10,
    freeDelivery: true,
    size: "4-Slot",
    tags: "charger,battery,intelligent"
  },
  {
    name: "Solar Power Bank 10000mAh",
    price: 1599,
    image: "https://via.placeholder.com/300?text=Solar+Power+Bank",
    category: "Power Solutions",
    brand: "SolarTech",
    color: "Black",
    inStock: true,
    stock: 30,
    badge: "Eco-Friendly",
    description: "10000mAh solar power bank with dual USB ports",
    discountPercent: 12,
    freeDelivery: true,
    offerPrice: 1407,
    size: "Portable",
    tags: "powerbank,solar,eco"
  },
  {
    name: "Wireless Charging Pad",
    price: 899,
    image: "https://via.placeholder.com/300?text=Charging+Pad",
    category: "Power Solutions",
    brand: "ChargeFast",
    color: "Black",
    inStock: true,
    stock: 45,
    isBestSeller: true,
    description: "15W fast wireless charging pad for all Qi-enabled devices",
    discountPercent: 8,
    freeDelivery: true,
    size: "Standard",
    tags: "wireless,charging,pad"
  },
  {
    name: "GaN Charger 65W USB-C",
    price: 2299,
    image: "https://via.placeholder.com/300?text=GaN+Charger",
    category: "Chargers",
    brand: "FastCharge",
    color: "White",
    inStock: true,
    stock: 25,
    isBestSeller: true,
    badge: "Ultra Fast",
    description: "65W GaN USB-C charger for laptops and phones",
    discountPercent: 15,
    freeDelivery: true,
    offerPrice: 1954,
    size: "Compact",
    tags: "charger,gan,fast"
  },
  {
    name: "Dock Charging Station Multi-Device",
    price: 1999,
    image: "https://via.placeholder.com/300?text=Dock+Station",
    category: "Chargers",
    brand: "DockPro",
    color: "Black",
    inStock: true,
    stock: 20,
    badge: "Organizer",
    description: "Multi-device charging dock for phone, tablet and watch",
    discountPercent: 10,
    freeDelivery: true,
    size: "Standard",
    tags: "dock,charging,multi-device"
  },
  {
    name: "Cable Type-C 3M 10Gbps",
    price: 599,
    image: "https://via.placeholder.com/300?text=USB+C+Cable",
    category: "Cables & Chargers",
    brand: "CableMax",
    color: "Black",
    inStock: true,
    stock: 55,
    description: "High-speed USB-C cable 3 meters with 10Gbps data transfer",
    discountPercent: 10,
    freeDelivery: true,
    size: "3M",
    tags: "cable,usb-c,data"
  },
  {
    name: "Network Switch 8-Port Gigabit",
    price: 2499,
    image: "https://via.placeholder.com/300?text=Network+Switch",
    category: "Networking",
    brand: "NetPro",
    color: "Black",
    inStock: true,
    stock: 18,
    description: "8-port gigabit ethernet switch with auto-sensing",
    discountPercent: 12,
    freeDelivery: true,
    size: "8-Port",
    tags: "switch,networking,ethernet"
  },
  {
    name: "Keyboard Mechanical RGB",
    price: 3999,
    image: "https://via.placeholder.com/300?text=Mechanical+KB",
    category: "Computer Accessories",
    brand: "MechPro",
    color: "Black",
    inStock: true,
    stock: 22,
    isBestSeller: true,
    badge: "Gaming",
    description: "Mechanical gaming keyboard with RGB backlighting and macro keys",
    discountPercent: 18,
    freeDelivery: true,
    offerPrice: 3279,
    size: "Full-Size",
    tags: "keyboard,mechanical,gaming"
  },
  {
    name: "Gaming Mouse RGB 16000DPI",
    price: 1799,
    image: "https://via.placeholder.com/300?text=Gaming+Mouse",
    category: "Computer Accessories",
    brand: "MouseGamer",
    color: "Black",
    inStock: true,
    stock: 40,
    isBestSeller: true,
    description: "Gaming mouse with 16000DPI sensor and RGB lighting",
    discountPercent: 15,
    freeDelivery: true,
    offerPrice: 1529,
    size: "Standard",
    tags: "mouse,gaming,dpi"
  },
  {
    name: "Laptop Stand Aluminum",
    price: 1299,
    image: "https://via.placeholder.com/300?text=Laptop+Stand",
    category: "Laptop Accessories",
    brand: "StandPro",
    color: "Silver",
    inStock: true,
    stock: 35,
    isBestSeller: true,
    badge: "Portable",
    description: "Portable aluminum laptop stand with adjustable height",
    discountPercent: 12,
    freeDelivery: true,
    offerPrice: 1143,
    size: "Universal",
    tags: "stand,laptop,portable"
  },
  {
    name: "USB Hub 7-Port with Power",
    price: 1199,
    image: "https://via.placeholder.com/300?text=USB+Hub+7",
    category: "Computer Accessories",
    brand: "HubMax",
    color: "Black",
    inStock: true,
    stock: 28,
    description: "7-port USB 3.0 hub with power adapter and independent switches",
    discountPercent: 10,
    freeDelivery: true,
    size: "One Size",
    tags: "hub,usb,powered"
  },
  {
    name: "Phone Lens Kit 3-in-1",
    price: 1599,
    image: "https://via.placeholder.com/300?text=Lens+Kit",
    category: "Phone Accessories",
    brand: "LensOptix",
    color: "Black",
    inStock: true,
    stock: 32,
    isBestSeller: true,
    badge: "Wide Angle",
    description: "3-in-1 phone lens kit with wide angle, macro and telephoto",
    discountPercent: 15,
    freeDelivery: true,
    offerPrice: 1359,
    size: "Universal",
    tags: "lens,phone,camera"
  },
  {
    name: "OLED Monitor 32 Inch 4K",
    price: 45999,
    image: "https://via.placeholder.com/300?text=OLED+Monitor",
    category: "Computer Accessories",
    brand: "DisplayMax",
    color: "Black",
    inStock: true,
    stock: 8,
    isBestSeller: true,
    badge: "Premium 4K",
    description: "32-inch OLED 4K monitor with 165Hz refresh rate",
    discountPercent: 20,
    freeDelivery: true,
    offerPrice: 36799,
    size: "32 Inch",
    tags: "monitor,oled,4k"
  }
];

async function seedAccessories() {
  try {
    // Connect to MongoDB
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing accessories (optional - comment out if you want to keep them)
    await Accessory.deleteMany({});
    console.log('Cleared existing accessories');

    // Insert accessories
    const result = await Accessory.insertMany(accessoriesData);
    console.log(`Successfully added ${result.length} accessories`);

    // Display summary
    console.log('\n✅ Accessories seeding completed!');
    console.log(`Total accessories: ${result.length}`);
    
    const stockSummary = await Accessory.aggregate([
      {
        $group: {
          _id: null,
          totalItems: { $sum: '$stock' },
          avgPrice: { $avg: '$price' },
          bestSellers: {
            $sum: { $cond: ['$isBestSeller', 1, 0] }
          }
        }
      }
    ]);

    if (stockSummary.length > 0) {
      const summary = stockSummary[0];
      console.log(`\nInventory Summary:`);
      console.log(`  - Total Stock: ${summary.totalItems} items`);
      console.log(`  - Average Price: ₹${Math.round(summary.avgPrice)}`);
      console.log(`  - Best Sellers: ${summary.bestSellers} products`);
    }

  } catch (error) {
    console.error('Error seeding accessories:', error.message);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('\nDatabase connection closed');
    process.exit(0);
  }
}

// Run the seeding script
seedAccessories();
