require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const electronicsProducts = [
  // Mobile Phones - Premium
  {
    name: 'iPhone 15 Pro Max',
    price: 159999,
    image: 'https://via.placeholder.com/300x300?text=iPhone+15+Pro+Max',
    category: 'Mobile Phones',
    brand: 'Apple',
    color: 'Space Black',
    inStock: true,
    stock: 25,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 149999,
    discountPercent: 6,
    badge: 'Best Seller',
    description: 'Latest iPhone 15 Pro Max with A17 Pro chip, advanced camera system.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.7"'
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    price: 149999,
    image: 'https://via.placeholder.com/300x300?text=Galaxy+S24+Ultra',
    category: 'Mobile Phones',
    brand: 'Samsung',
    color: 'Phantom Black',
    inStock: true,
    stock: 30,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 139999,
    discountPercent: 7,
    badge: 'Best Seller',
    description: 'Samsung Galaxy S24 Ultra with 200MP camera and dynamic AMOLED display.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.8"'
  },
  {
    name: 'Google Pixel 8 Pro',
    price: 119999,
    image: 'https://via.placeholder.com/300x300?text=Pixel+8+Pro',
    category: 'Mobile Phones',
    brand: 'Google',
    color: 'Obsidian',
    inStock: true,
    stock: 20,
    isOffer: false,
    isBestSeller: true,
    badge: 'Popular',
    description: 'Google Pixel 8 Pro with advanced AI features and computational photography.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.7"'
  },
  {
    name: 'OnePlus 12',
    price: 69999,
    image: 'https://via.placeholder.com/300x300?text=OnePlus+12',
    category: 'Mobile Phones',
    brand: 'OnePlus',
    color: 'Silky Black',
    inStock: true,
    stock: 35,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 59999,
    discountPercent: 14,
    badge: 'Great Value',
    description: 'OnePlus 12 with Snapdragon 8 Gen 3 and 120Hz AMOLED display.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.7"'
  },
  {
    name: 'Xiaomi 14 Ultra',
    price: 89999,
    image: 'https://via.placeholder.com/300x300?text=Xiaomi+14+Ultra',
    category: 'Mobile Phones',
    brand: 'Xiaomi',
    color: 'Black',
    inStock: true,
    stock: 28,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 79999,
    discountPercent: 11,
    badge: 'Camera King',
    description: 'Xiaomi 14 Ultra with Leica camera system and ultra-fast charging.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.73"'
  },
  {
    name: 'POCO X6 Pro',
    price: 35999,
    image: 'https://via.placeholder.com/300x300?text=POCO+X6+Pro',
    category: 'Mobile Phones',
    brand: 'POCO',
    color: 'Space Gray',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 29999,
    discountPercent: 17,
    badge: 'Best Budget',
    description: 'POCO X6 Pro with 144Hz display and MediaTek Dimensity processor.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '6.67"'
  },

  // Laptops - Premium
  {
    name: 'MacBook Pro 16" M3 Max',
    price: 249999,
    image: 'https://via.placeholder.com/300x300?text=MacBook+Pro+16',
    category: 'Laptops',
    brand: 'Apple',
    color: 'Space Black',
    inStock: true,
    stock: 15,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 239999,
    discountPercent: 4,
    badge: 'Premium',
    description: 'MacBook Pro 16" with M3 Max chip, 36GB memory, 512GB SSD.',
    freeDelivery: false,
    deliveryPrice: 500,
    size: '16"'
  },
  {
    name: 'Dell XPS 15',
    price: 179999,
    image: 'https://via.placeholder.com/300x300?text=Dell+XPS+15',
    category: 'Laptops',
    brand: 'Dell',
    color: 'Platinum Silver',
    inStock: true,
    stock: 18,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 169999,
    discountPercent: 6,
    badge: 'Best Seller',
    description: 'Dell XPS 15 with Intel i9, RTX 4090, 32GB RAM, OLED display.',
    freeDelivery: false,
    deliveryPrice: 500,
    size: '15.6"'
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon',
    price: 149999,
    image: 'https://via.placeholder.com/300x300?text=ThinkPad+X1',
    category: 'Laptops',
    brand: 'Lenovo',
    color: 'Black',
    inStock: true,
    stock: 25,
    isOffer: false,
    isBestSeller: true,
    badge: 'Business',
    description: 'Lenovo ThinkPad X1 Carbon with Intel i7, 16GB RAM, lightweight design.',
    freeDelivery: false,
    deliveryPrice: 400,
    size: '14"'
  },
  {
    name: 'ASUS ROG Zephyrus G16',
    price: 199999,
    image: 'https://via.placeholder.com/300x300?text=ASUS+ROG+G16',
    category: 'Laptops',
    brand: 'ASUS',
    color: 'Eclipse Gray',
    inStock: true,
    stock: 12,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 189999,
    discountPercent: 5,
    badge: 'Gaming',
    description: 'ASUS ROG Zephyrus G16 with RTX 4090, Intel i9, 240Hz display.',
    freeDelivery: false,
    deliveryPrice: 500,
    size: '16"'
  },
  {
    name: 'HP Pavilion 15',
    price: 59999,
    image: 'https://via.placeholder.com/300x300?text=HP+Pavilion+15',
    category: 'Laptops',
    brand: 'HP',
    color: 'Natural Silver',
    inStock: true,
    stock: 40,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 49999,
    discountPercent: 17,
    badge: 'Budget',
    description: 'HP Pavilion 15 with AMD Ryzen 5, 8GB RAM, 512GB SSD.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '15.6"'
  },
  {
    name: 'Acer Aspire 5',
    price: 49999,
    image: 'https://via.placeholder.com/300x300?text=Acer+Aspire+5',
    category: 'Laptops',
    brand: 'Acer',
    color: 'Steel Gray',
    inStock: true,
    stock: 35,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 44999,
    discountPercent: 10,
    badge: 'Value',
    description: 'Acer Aspire 5 with Intel i5, 8GB RAM, 512GB SSD, great for daily use.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '15.6"'
  },

  // Smart Watches
  {
    name: 'Apple Watch Series 9',
    price: 39999,
    image: 'https://via.placeholder.com/300x300?text=Apple+Watch+9',
    category: 'Smart Watches',
    brand: 'Apple',
    color: 'Midnight',
    inStock: true,
    stock: 40,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 35999,
    discountPercent: 10,
    badge: 'Best Seller',
    description: 'Apple Watch Series 9 with always-on display, fitness tracking, ECG.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '41mm'
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    price: 29999,
    image: 'https://via.placeholder.com/300x300?text=Galaxy+Watch+6',
    category: 'Smart Watches',
    brand: 'Samsung',
    color: 'Black',
    inStock: true,
    stock: 35,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 24999,
    discountPercent: 17,
    badge: 'Popular',
    description: 'Samsung Galaxy Watch 6 Classic with rotating bezel, health monitoring.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '47mm'
  },
  {
    name: 'Garmin Epix Gen 2',
    price: 49999,
    image: 'https://via.placeholder.com/300x300?text=Garmin+Epix',
    category: 'Smart Watches',
    brand: 'Garmin',
    color: 'Titanium',
    inStock: true,
    stock: 20,
    isOffer: false,
    isBestSeller: false,
    badge: 'Sports',
    description: 'Garmin Epix Gen 2 with AMOLED display, advanced sports features.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '47mm'
  },
  {
    name: 'Fitbit Sense 2',
    price: 24999,
    image: 'https://via.placeholder.com/300x300?text=Fitbit+Sense+2',
    category: 'Smart Watches',
    brand: 'Fitbit',
    color: 'Midnight',
    inStock: true,
    stock: 45,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 19999,
    discountPercent: 20,
    badge: 'Health',
    description: 'Fitbit Sense 2 with EDA sensor, stress management, sleep tracking.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: 'One Size'
  },
  {
    name: 'Huawei Watch GT 4',
    price: 19999,
    image: 'https://via.placeholder.com/300x300?text=Huawei+Watch+GT4',
    category: 'Smart Watches',
    brand: 'Huawei',
    color: 'Black',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 16999,
    discountPercent: 15,
    badge: 'Battery King',
    description: 'Huawei Watch GT 4 with 14-day battery life, AMOLED display.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '46mm'
  },

  // Mobile Accessories
  {
    name: 'USB-C Fast Charger 65W',
    price: 2999,
    image: 'https://via.placeholder.com/300x300?text=USB-C+Charger',
    category: 'Mobile Accessories',
    brand: 'Anker',
    color: 'Black',
    inStock: true,
    stock: 150,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 2299,
    discountPercent: 23,
    badge: 'Fast Charging',
    description: '65W USB-C fast charger compatible with all devices.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Phone Case Protective',
    price: 999,
    image: 'https://via.placeholder.com/300x300?text=Phone+Case',
    category: 'Mobile Accessories',
    brand: 'Spigen',
    color: 'Black',
    inStock: true,
    stock: 200,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 699,
    discountPercent: 30,
    badge: 'Protection',
    description: 'Heavy-duty protective phone case with shock absorption.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Screen Protector Glass',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Screen+Protector',
    category: 'Mobile Accessories',
    brand: 'Nillkin',
    color: 'Clear',
    inStock: true,
    stock: 250,
    isOffer: false,
    isBestSeller: true,
    badge: 'Essential',
    description: 'Tempered glass screen protector with anti-fingerprint coating.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Wireless Phone Charger',
    price: 1999,
    image: 'https://via.placeholder.com/300x300?text=Wireless+Charger',
    category: 'Mobile Accessories',
    brand: 'Belkin',
    color: 'White',
    inStock: true,
    stock: 80,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1499,
    discountPercent: 25,
    badge: 'Convenient',
    description: '15W wireless charging pad for all Qi-enabled phones.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'USB-C Cable 3m',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=USB-C+Cable',
    category: 'Mobile Accessories',
    brand: 'Anker',
    color: 'Black',
    inStock: true,
    stock: 300,
    isOffer: false,
    isBestSeller: false,
    badge: 'Durable',
    description: '3m high-quality USB-C cable with fast data transfer.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '3m'
  },
  {
    name: 'Pop Socket Phone Grip',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=Pop+Socket',
    category: 'Mobile Accessories',
    brand: 'PopSockets',
    color: 'Multi-color',
    inStock: true,
    stock: 180,
    isOffer: false,
    isBestSeller: false,
    badge: 'Stylish',
    description: 'Expandable pop socket grip stand for phones and tablets.',
    freeDelivery: true,
    deliveryPrice: 0
  },

  // Laptop Accessories
  {
    name: 'Laptop Stand Adjustable',
    price: 2499,
    image: 'https://via.placeholder.com/300x300?text=Laptop+Stand',
    category: 'Laptop Accessories',
    brand: 'Lamicall',
    color: 'Silver',
    inStock: true,
    stock: 70,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 1799,
    discountPercent: 28,
    badge: 'Ergonomic',
    description: 'Adjustable aluminum laptop stand for better ergonomics.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Wireless Mouse 2.4GHz',
    price: 1499,
    image: 'https://via.placeholder.com/300x300?text=Wireless+Mouse',
    category: 'Laptop Accessories',
    brand: 'Logitech',
    color: 'Black',
    inStock: true,
    stock: 120,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 999,
    discountPercent: 33,
    badge: 'Precision',
    description: '2.4GHz wireless mouse with precise tracking and long battery life.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'USB-C Hub 7 in 1',
    price: 3999,
    image: 'https://via.placeholder.com/300x300?text=USB+Hub',
    category: 'Laptop Accessories',
    brand: 'Anker',
    color: 'Silver',
    inStock: true,
    stock: 60,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 2999,
    discountPercent: 25,
    badge: 'Connectivity',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Laptop Cooling Pad',
    price: 2199,
    image: 'https://via.placeholder.com/300x300?text=Cooling+Pad',
    category: 'Laptop Accessories',
    brand: 'HAVIT',
    color: 'Black',
    inStock: true,
    stock: 85,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1699,
    discountPercent: 23,
    badge: 'Thermal',
    description: 'Laptop cooling pad with 5 ultra-quiet fans.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Laptop Backpack 17"',
    price: 2999,
    image: 'https://via.placeholder.com/300x300?text=Laptop+Backpack',
    category: 'Laptop Accessories',
    brand: 'Targus',
    color: 'Black',
    inStock: true,
    stock: 95,
    isOffer: false,
    isBestSeller: false,
    badge: 'Travel',
    description: 'Durable laptop backpack with multiple compartments for 17" laptops.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '17"'
  },
  {
    name: 'Mechanical Keyboard RGB',
    price: 5999,
    image: 'https://via.placeholder.com/300x300?text=Mechanical+Keyboard',
    category: 'Laptop Accessories',
    brand: 'Corsair',
    color: 'Black',
    inStock: true,
    stock: 45,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 4999,
    discountPercent: 17,
    badge: 'Gaming',
    description: 'Mechanical RGB keyboard with Cherry MX switches and wireless connection.',
    freeDelivery: true,
    deliveryPrice: 0
  },

  // Watch Accessories
  {
    name: 'Watch Band Silicone',
    price: 799,
    image: 'https://via.placeholder.com/300x300?text=Watch+Band',
    category: 'Watch Accessories',
    brand: 'Bandley',
    color: 'Multi-color',
    inStock: true,
    stock: 150,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 499,
    discountPercent: 38,
    badge: 'Style',
    description: 'Soft silicone watch band compatible with most smartwatches.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Watch Charger Magnetic',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Watch+Charger',
    category: 'Watch Accessories',
    brand: 'Helix',
    color: 'Black',
    inStock: true,
    stock: 100,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 899,
    discountPercent: 31,
    badge: 'Charging',
    description: 'Magnetic wireless watch charger with fast charging capability.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Screen Protector Watch',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=Watch+Protector',
    category: 'Watch Accessories',
    brand: 'Spigen',
    color: 'Clear',
    inStock: true,
    stock: 120,
    isOffer: false,
    isBestSeller: false,
    badge: 'Protection',
    description: 'Tempered glass screen protector for smartwatches.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Watch Face Metal',
    price: 1599,
    image: 'https://via.placeholder.com/300x300?text=Watch+Face',
    category: 'Watch Accessories',
    brand: 'Ztop',
    color: 'Silver',
    inStock: true,
    stock: 80,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1199,
    discountPercent: 25,
    badge: 'Premium',
    description: 'Premium stainless steel watch case with metal frame.',
    freeDelivery: true,
    deliveryPrice: 0
  },

  // Tablets
  {
    name: 'iPad Pro 12.9" M2',
    price: 99999,
    image: 'https://via.placeholder.com/300x300?text=iPad+Pro+12',
    category: 'Tablets',
    brand: 'Apple',
    color: 'Space Gray',
    inStock: true,
    stock: 20,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 94999,
    discountPercent: 5,
    badge: 'Best Seller',
    description: 'iPad Pro 12.9" with M2 chip, Liquid Retina XDR display, 256GB.',
    freeDelivery: false,
    deliveryPrice: 300,
    size: '12.9"'
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra',
    price: 89999,
    image: 'https://via.placeholder.com/300x300?text=Galaxy+Tab+S9',
    category: 'Tablets',
    brand: 'Samsung',
    color: 'Gray',
    inStock: true,
    stock: 18,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 79999,
    discountPercent: 11,
    badge: 'Display',
    description: 'Samsung Galaxy Tab S9 Ultra with 120Hz display, Snapdragon 8 Gen 2.',
    freeDelivery: false,
    deliveryPrice: 300,
    size: '14.6"'
  },
  {
    name: 'Lenovo Tab P11 Pro',
    price: 49999,
    image: 'https://via.placeholder.com/300x300?text=Lenovo+Tab+P11',
    category: 'Tablets',
    brand: 'Lenovo',
    color: 'Black',
    inStock: true,
    stock: 30,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 44999,
    discountPercent: 10,
    badge: 'Value',
    description: 'Lenovo Tab P11 Pro with OLED display, 8GB RAM, 256GB storage.',
    freeDelivery: false,
    deliveryPrice: 200,
    size: '11.5"'
  },

  // Earbuds & Speakers
  {
    name: 'Apple AirPods Pro 2',
    price: 29999,
    image: 'https://via.placeholder.com/300x300?text=AirPods+Pro+2',
    category: 'Audio',
    brand: 'Apple',
    color: 'White',
    inStock: true,
    stock: 50,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 26999,
    discountPercent: 10,
    badge: 'Best Seller',
    description: 'Apple AirPods Pro 2 with active noise cancellation and spatial audio.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    price: 34999,
    image: 'https://via.placeholder.com/300x300?text=Sony+WH1000XM5',
    category: 'Audio',
    brand: 'Sony',
    color: 'Black',
    inStock: true,
    stock: 35,
    isOffer: true,
    isBestSeller: true,
    offerPrice: 31999,
    discountPercent: 9,
    badge: 'Noise Cancel',
    description: 'Sony WH-1000XM5 with industry-leading noise cancellation.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'Samsung Galaxy Buds Pro 2',
    price: 19999,
    image: 'https://via.placeholder.com/300x300?text=Galaxy+Buds+Pro+2',
    category: 'Audio',
    brand: 'Samsung',
    color: 'Black',
    inStock: true,
    stock: 60,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 16999,
    discountPercent: 15,
    badge: 'Premium Sound',
    description: 'Samsung Galaxy Buds Pro 2 with 360 audio and IPX7 water resistance.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'JBL Charge 5 Bluetooth Speaker',
    price: 14999,
    image: 'https://via.placeholder.com/300x300?text=JBL+Charge+5',
    category: 'Audio',
    brand: 'JBL',
    color: 'Black',
    inStock: true,
    stock: 75,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 12999,
    discountPercent: 13,
    badge: 'Portable',
    description: 'JBL Charge 5 portable speaker with 20-hour battery life.',
    freeDelivery: true,
    deliveryPrice: 0
  },

  // Cables & Adapters
  {
    name: 'Lightning Cable 2m',
    price: 1299,
    image: 'https://via.placeholder.com/300x300?text=Lightning+Cable',
    category: 'Cables & Adapters',
    brand: 'Belkin',
    color: 'White',
    inStock: true,
    stock: 200,
    isOffer: false,
    isBestSeller: true,
    badge: 'Official',
    description: 'MFi certified Lightning cable for fast charging and data transfer.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '2m'
  },
  {
    name: 'HDMI 2.1 Cable 3m',
    price: 1799,
    image: 'https://via.placeholder.com/300x300?text=HDMI+Cable',
    category: 'Cables & Adapters',
    brand: 'Belkin',
    color: 'Black',
    inStock: true,
    stock: 150,
    isOffer: true,
    isBestSeller: false,
    offerPrice: 1399,
    discountPercent: 22,
    badge: '4K/8K',
    description: 'HDMI 2.1 cable supporting 4K@120Hz and 8K@60Hz.',
    freeDelivery: true,
    deliveryPrice: 0,
    size: '3m'
  },
  {
    name: 'USB 3.0 Hub 4 Port',
    price: 999,
    image: 'https://via.placeholder.com/300x300?text=USB+Hub',
    category: 'Cables & Adapters',
    brand: 'Anker',
    color: 'Silver',
    inStock: true,
    stock: 120,
    isOffer: false,
    isBestSeller: false,
    badge: 'Connectivity',
    description: '4-port USB 3.0 hub with high-speed data transfer.',
    freeDelivery: true,
    deliveryPrice: 0
  },
  {
    name: 'USB-A to USB-C Adapter',
    price: 299,
    image: 'https://via.placeholder.com/300x300?text=USB+Adapter',
    category: 'Cables & Adapters',
    brand: 'Anker',
    color: 'Black',
    inStock: true,
    stock: 300,
    isOffer: false,
    isBestSeller: false,
    badge: 'Essential',
    description: 'USB-A to USB-C adapter for universal compatibility.',
    freeDelivery: true,
    deliveryPrice: 0
  }
];

mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    try {
      // Clear existing products and add new electronics products
      await Product.deleteMany({});
      console.log('Cleared existing products');

      // Insert electronics products
      const products = await Product.insertMany(electronicsProducts);
      console.log(`✅ Successfully added ${products.length} electronics products!`);
      
      // Display products by category
      const categories = {};
      products.forEach(p => {
        if (!categories[p.category]) categories[p.category] = [];
        categories[p.category].push(p.name);
      });

      console.log('\n📱 Products by Category:');
      Object.entries(categories).forEach(([category, items]) => {
        console.log(`\n${category}: (${items.length} products)`);
        items.forEach((name, idx) => console.log(`  ${idx + 1}. ${name}`));
      });

      // Get total product count
      const totalProducts = await Product.countDocuments();
      console.log(`\n📊 Total products in database: ${totalProducts}`);

      process.exit(0);
    } catch (err) {
      console.error('Error:', err.message);
      process.exit(1);
    }
  })
  .catch(err => {
    console.error('MongoDB connection error:', err.message);
    process.exit(1);
  });
