const Bill = require('../models/Bill');
const Order = require('../models/Order');

// Helper to resolve user display name safely
function resolveUserName(user) {
  return (user && user.profile && user.profile.name) ? user.profile.name : (user && (user.name || user.email) || 'Customer');
}

async function createBillForOrder(orderId, userId, order) {
  try {
    const User = require('../models/User');
    const user = await User.findById(userId);
    if (!user) {
      throw new Error('User not found for bill creation');
    }

    const resolvedUserName = resolveUserName(user);

    // Prepare bill items
    const billItems = order.items.map(item => ({
      productId: item.product,
      productName: item.productName || item.productName || 'Product',
      quantity: item.quantity,
      unitPrice: item.price,
      totalPrice: item.price * item.quantity
    }));

    const subtotal = order.total || billItems.reduce((s, it) => s + (it.totalPrice || 0), 0);
    const tax = 0; // Default tax, can be customized
    const shippingCost = 0;
    const discount = 0;

    // Generate a billNumber here to avoid relying only on pre-save hooks (avoids race/validation issues)
    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const uniquePart = Date.now();
    const billNumber = `BILL-${year}${month}-${String(uniquePart).slice(-8)}`;

    const bill = await Bill.create({
      billNumber,
      order: orderId,
      user: userId,
      userEmail: user.email || '',
      userName: resolvedUserName,
      userAddress: order.address,
      items: billItems,
      subtotal,
      tax,
      shippingCost,
      discount,
      total: subtotal + tax + shippingCost - discount,
      paymentMethod: 'Online',
      isAutoGenerated: true,
      status: 'Pending'
    });

    console.log('Bill created successfully:', bill._id);

    // Link the bill back to the order record so it's easy to find from the order
    try {
      await Order.findByIdAndUpdate(orderId, { $set: { bill: bill._id } });
    } catch (linkErr) {
      console.error('Failed to link bill to order', orderId, linkErr && linkErr.message ? linkErr.message : linkErr);
    }

    return bill;
  } catch (err) {
    console.error(`Error creating bill for order ${orderId}, user ${userId}:`, err && err.stack ? err.stack : err);
    throw err;
  }
}

module.exports = { createBillForOrder, resolveUserName };
