const accessoriesData = [
 {
    id: "201",
    name: "Wireless Earbuds",
    image: "/images/accessory_noid_wireless_earbuds.jpg",
    images:[
      "/images/accessory_noid_wireless_earbuds.jpg",
      "/images/accessory_noid_wireless_earbuds.jpg",
      "/images/accessory_noid_wireless_earbuds.jpg",
      "/images/accessory_noid_wireless_earbuds.jpg"
    ],
    price: 1499,
     rating: 4.5,
    category: "Mobile Accessories",
    brand: "boat",
    color: "Balck",
    inStock: true,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "High quality wireless earbuds for your mobile devices."
  },
  {
    id: "202",
    name: "Fast Charging Cable",
    image: "/images/accessory_noid_fast_charging_cable.jpg",
    images: [ 
    "/images/accessory_noid_fast_charging_cable.jpg",
    "/images/accessory_noid_fast_charging_cable.jpg",
    "/images/accessory_noid_fast_charging_cable.jpg",
    "/images/accessory_noid_fast_charging_cable.jpg"
    ],
    price: 399,
    rating: 4.2,
    category: "Mobile Accessories",
    brand: "Xiaomi",
    color: "white",
    inStock: true,
    isOffer: false,
    isBestSeller: true,
    badge: "Best seller",
    description: "Durable and fast charging cable compatible with most phones."
  },
  {
    id: "203",
    name: "Phone Case",
    image: "/images/accessory_noid_phone_case.jpg",
    images:[
      "/images/accessory_noid_phone_case.jpg",
      "/images/accessory_noid_phone_case.jpg"
    ],
    price: 299,
    rating: 4.0,
    category: "Mobile Accessories",
    brand: "i phone ",
    color: "pink",
    inStock: true,
    isOffer: false,
    isBestSeller: true,
    badge: "Best seller",
    description: "Protective phone case with stylish design."
  },
  {
    id: "204",
    name: "Screen Protector",
    image: "/images/accessory_noid_screen_protector_data.jpg",
    price: 199,
    rating: 4.3,
    category: "Mobile Accessories",
    brand: "",
    color: "",
    inStock: true,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "Tempered glass screen protector for extra safety."
  },
  {
    id: "205",
    name: "Bluetooth Speaker",
    image: "/images/accessory_noid_bluetooth_speaker_data.jpg",
    price: 1799,
    rating: 4.6,
    category: "Audio",
    brand: "Xiaomi",
    color: "Balck",
    inStock: true,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "Portable Bluetooth speaker with deep bass and long battery life."
  },
  {
    id: "206",
    name: "Car Mount Holder",
    image: "/images/accessory_noid_car_mount_holder_data.jpg",
    price: 499,
    rating: 4.1,
    category: "Car Accessories",
    brand: "",
    color: "",
    inStock: false,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "Securely mount your phone in your car for easy navigation."
  },
  {
    id: "207",
    name: "Power Bank 10000mAh",
    image: "/images/accessory_noid_power_bank_10000mah_data.jpg",
    price: 1299,
    rating: 4.4,
    category: "Power",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "High-capacity power bank for charging on the go."
  },
  {
    id: "208",
    name: "Selfie Stick",
    image: "/images/accessory_noid_selfie_stick_data.jpg",
    price: 399,
    rating: 4.9,
    category: "Photography",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Extendable selfie stick with Bluetooth remote."
  },
  {
    id: "209",
    name: "Wireless Charging Pad",
    image: "/images/product_107_oneplus_pad.jpg",
    price: 999,
    rating: 4.2,
    category: "Power",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: true,
    badge: "Best seller",
    description: "Convenient wireless charging for compatible devices."
  },
  {
    id: "210",
    name: "Magnetic Phone Holder",
    image: "/images/accessory_noid_magnetic_phone_holder.jpg",
    price: 499,
    rating: 4.1,
    category: "Car Accessories",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: true,
    badge: "Best seller",
    description: "Magnetic holder for easy phone mounting in your car."
  },
  {
    id: "211",
    name: "Gaming Trigger",
    image: "/images/accessory_noid_gaming_trigger.jpg",
    price: 299,
    rating: 4.0,
    category: "Gaming",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Responsive gaming trigger for mobile shooters."
  },
  {
    id: "212",
    name: "Foldable Tablet Stand",
    image: "/images/accessory_noid_foldable_tablet_stand.jpg",
    price: 699,
    rating: 4.3,
    category: "Stands",
    brand: "",
    color: "",
    inStock: false,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "Adjustable stand for tablets and large phones."
  },
  {
    id: "213",
    name: "OTG Adapter",
    image: "/images/accessory_noid_otg_adapter.jpg",
    price: 199,
    rating: 4.2,
    category: "Adapters",
    brand: "",
    color: "",
    inStock: false,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "USB OTG adapter for connecting peripherals."
  },
  {
    id: "214",
    name: "Smartwatch Band",
    image: "/images/accessory_noid_smartwatch_band.jpg",
    price: 349,
    rating: 4.4,
    category: "Wearables",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Comfortable and stylish smartwatch replacement band."
  },
  {
    id: "215",
    name: "Mobile Cleaning Kit",
    image: "/images/accessory_noid_mobile_cleaning_kit.jpg",
    price: 249,
    rating: 4.1,
    category: "Cleaning",
     brand: "",
    color: "",
    inStock: false,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Complete cleaning kit for screens and devices."
  },
  {
    id: "216",
    name: "Noise Cancelling Headphones",
    image: [
      "https://m.media-amazon.com/images/I/41-LcaT-aKL._SX300_SY300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/71VxtLNVqWL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61CsQ+m9u1L._SL1500_.jpg"
    ],
    price: 3499,
    rating: 4.7,
    category: "Audio",
     brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Over-ear headphones with active noise cancellation."
  },
  {
    id: "217",
    name: "Pop Socket",
    image: "/images/accessory_noid_pop_socket.jpg",
    price: 199,
    rating: 4.0,
    category: "Mobile Accessories",
    brand: "",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Handy pop socket for better phone grip."
  },
  {
    id: "218",
    name: "Dual USB Car Charger",
    image: "/images/accessory_noid_dual_usb_car_charger.jpg",
    price: 399,
    rating: 4.3,
    category: "Car Accessories",
    brand: "",
    color: "",
    inStock: false,
    isOffer: true,
    isBestSeller: false,
    badge: "Offer",
    description: "Charge two devices simultaneously in your car."
  },
  {
    id: "219",
    name: "Wireless Keyboard",
    image: "/images/accessory_noid_wireless_keyboard.jpg",
    price: 1599,
    rating: 4.5,
    category: "Keyboards",
    brand: "HP",
    color: "",
    inStock: true,
    isOffer: false,
    isBestSeller: false,
    badge: "",
    description: "Slim wireless keyboard for tablets and phones."
  }
];

export default accessoriesData;