const mongoose = require('mongoose');

const BillSchema = new mongoose.Schema({
  billNumber: { 
    type: String, 
    unique: true, 
    required: true,
    index: true 
  },
  order: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Order',
    required: true 
  },
  user: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },
  userEmail: { 
    type: String, 
    required: true 
  },
  userName: { 
    type: String, 
    required: true 
  },
  userAddress: { 
    type: String 
  },
  items: [
    {
      productId: { type: mongoose.Schema.Types.ObjectId },
      productName: { type: String, required: true },
      quantity: { type: Number, required: true },
      unitPrice: { type: Number, required: true },
      totalPrice: { type: Number, required: true }
    }
  ],
  subtotal: { 
    type: Number, 
    required: true 
  },
  tax: { 
    type: Number, 
    default: 0 
  },
  taxPercentage: { 
    type: Number, 
    default: 0 
  },
  shippingCost: { 
    type: Number, 
    default: 0 
  },
  discount: { 
    type: Number, 
    default: 0 
  },
  total: { 
    type: Number, 
    required: true 
  },
  billDate: { 
    type: Date, 
    default: Date.now 
  },
  dueDate: { 
    type: Date 
  },
  status: { 
    type: String, 
    enum: ['Pending', 'Paid', 'Partial', 'Overdue', 'Cancelled'],
    default: 'Pending' 
  },
  paymentMethod: { 
    type: String,
    enum: ['Cash', 'Card', 'Bank Transfer', 'Online'],
    default: 'Online'
  },
  notes: { 
    type: String 
  },
  isAutoGenerated: { 
    type: Boolean, 
    default: true 
  },
  createdBy: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User'
  }
}, { timestamps: true });

// Auto-generate bill number before saving
BillSchema.pre('save', async function(next) {
  if (this.isNew && !this.billNumber) {
    try {
      const count = await this.constructor.countDocuments();
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      this.billNumber = `BILL-${year}${month}-${String(count + 1).padStart(5, '0')}`;
    } catch (err) {
      // Fallback: ensure billNumber set to a timestamp-based value if count fails
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      this.billNumber = `BILL-${year}${month}-${String(Date.now()).slice(-8)}`;
      console.warn('Could not generate sequential bill number, used fallback:', this.billNumber, err && err.message ? err.message : err);
    }
  }
  next();
});

module.exports = mongoose.model('Bill', BillSchema);
